version: 0.2
phases:
 install:
   commands:
     - |
         export DEBIAN_FRONTEND=noninteractive
         #Install php7.1
         apt-get update
         apt-get install -y software-properties-common libpng-dev libicu-dev libpq-dev libxml2-dev libxslt-dev supervisor apache2  build-essential wget git --no-install-recommends
         LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
         apt-get update
         # Install PHP
         apt-get install -y vim supervisor apache2 curl php7.2 php7.2-zip php7.2-curl php7.2-opcache php7.2-gd php7.2-json php7.2-mysql php7.2-pgsql php7.2-sqlite3 php7.2-xml php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-ctype php7.2-intl iproute2 build-essential wget git curl unzip
         # Install Composer
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
 build:
   commands:
     - echo Build started on `date`
#     - composer install

 post_build:
   commands:
     - echo Build completed on `date`

artifacts:
  files:
    - main
    - appspec.yml
    - buildspec.yml
    - codedeploy/*
